version: 2

jobs:
  build_test_deploy:
    docker:
      - image: circleci/node:10.15.2
    environment:
      TZ: "/usr/share/zoneinfo/Australia/Melbourne"
    steps:
      - checkout
      - restore_cache:
          key: v1-dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: v1-dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: npm test
      - run: npm run build
      - add_ssh_keys:
          fingerprints:
            - "19:67:f8:5d:eb:78:f8:61:36:fe:d8:02:bc:19:1d:cc"
      - run: npm run deploy

workflows:
  version: 2
  build_test_deploy:
      jobs:
        - build_test_deploy:
            filters:
              branches:
                ignore: gh-pages
